# -*- coding: utf-8 -*-
"""MediFind Deploy - PaddleOCR .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMSxIif3gTEgsoPEDtO1xaKpIgR1M8CV
"""


# !python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
# !pip install "paddleocr>=2.1.0"

from paddleocr import PaddleOCR,draw_ocr
import cv2
from PIL import Image


# Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# You can set the parameter `lang` as `ch`, `en`, `fr`, `german`, `korean`, `japan`
# to switch the language model in order.
ocr = PaddleOCR(use_angle_cls=True, lang='en')
font_path = './fonts/simfang.ttf'# need to run only once to download and load model into memory



img_path = './test_img.jpg'
img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
# cv2_imshow(img)
result = ocr.ocr(img_path, cls=True)

for line in result:
    print(line)

# draw result
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]

#font = ImageFont.load_default()
im_show = draw_ocr(image, boxes, txts, scores,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result1.jpg')

res_path = './result1.jpg'
img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
cv2.imshow(img)